<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>

<body>
  <h1>鏈接技巧</h1>
  <h3>1. Promise Chain : 執行若失敗直接轉到 .catch 繼續執行 return</h3>
  <h3>2. .then 同時接收成功 & 失敗結果, 大多數使用成功結果</h3>

  <script>

    function promiseFn(num) {
      return new Promise((resolve, reject) => {

        setTimeout(() => {
          if (num) {
            resolve(`成功 ${num}`);
          } else {
            reject('失敗')
          }
        }, 0);
      })
    }

    // 1. Promise Chain
    function sample_promiseChain(){
      promiseFn(1)
        // 1.
        // .then(res => {
        //     console.log("res:", res);
        //     return promiseFn(2); // 透過 return 進行串接
        //   })
        // .then(res => {
        //   console.log("res:", res);
        //   return promiseFn(3);
        // })
        // .then(res => {
        //   console.log("res:", res);
        // })


        // 2.
        .then(res => {
          console.log("res:", res);
          return promiseFn(0); // 失敗直接轉到 .catch 繼續執行 return
        })
        .then(res => {
          console.log("res:", res);
          return promiseFn(2);
        })
        .catch(rej => {
          console.log('catch -', rej);
          return promiseFn(4);  // 新的Promise行為會屬於另一個鏈
        })
        .then(res => {
          console.log("res:", res);
        })
    }


    // 2. then 同時接收成功 & 失敗 結果
    function sample_promiseChain2(){
      promiseFn(0)
        .then(
          (res)=> { // 成功執行 return promiseFn(3)
          console.log('success -', res);
          return promiseFn(3);
        }, (rej)=> {  // 失敗執行 return promiseFn(4)
          console.log('fail -', rej);
          return promiseFn(4);
        })
  
        .then(
          (res) => {
          console.log('success -', res);
        }, (rej) => {
          console.log('fail -', rej);
        })
    }

  </script>
</body>

</html>